version: "3.8"

services:
  app:
    image: defaultapp
    environment:
      MONGO_URL: "mongodb://db:27017/test"
    depends_on:
      - db
    ports:
      - "3000-3010:3000"

  db:
    image: mongo
